version: '3'
services:
  api:
    build:
      context: api/foodordering
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD="${POSTGRES_PASSWORD}"
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - spring-postgres
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
    ports:
      - 5432:5432
    volumes:
      - foodordering-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
volumes:
  foodordering-data:
networks:
  spring-postgres:
